tangcent/easy-yapi

common-api/src/main/kotlin/com/itangcent/common/constant/Attrs.kt
idea-plugin/build.gradle
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/YapiExportAction.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/intellij/extend/AnyKit.kt
idea-plugin/src/main/resources/.recommend.easy.api.config
src/main/resources/META-INF/services/com.itangcent.common.SetupAble

support new rule `field.mock`

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt

`switch_notice` are supported after yapi v1.9.1 :https://github.com/YMFE/yapi/issues/1729
PR: https://github.com/YMFE/yapi/pull/1646

feat: `switch_notice` for yapi export

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt

fix: preserving the order of field in `YapiFormatter`

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/EasyApiConfigReader.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanConfigReader.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/DebugDialog.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/StandardJdkRuleParser.kt
idea-plugin/src/main/kotlin/com/itangcent/utils/Initializable.kt
idea-plugin/src/main/resources/META-INF/plugin.xml

- opti: support new rule `postman.prerequest`&`postman.test` [(#283)](https://github.com/tangcent/easy-api/pull/283)
- opti: support new rule tool `config` [(#284)](https://github.com/tangcent/easy-api/pull/284)
- fix: preserving the order of field in `YapiFormatter` [(#189)](https://github.com/tangcent/easy-yapi/pull/189)
- opti: input new token if the old one be deleted. [(#192)](https://github.com/tangcent/easy-yapi/pull/192)

release v1.9.5.0.183.0

---

IDEA_CHANGELOG.md
build.gradle
common-api/build.gradle
gradle.properties
idea-plugin/build.gradle
idea-plugin/parts/pluginChanges.html
idea-plugin/parts/pluginDescription.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: support new rule `export.after`   [(#198)](https://github.com/tangcent/easy-yapi/pull/198)
* fix: yapi formatPath allow `?`&`=`  [(#200)](https://github.com/tangcent/easy-yapi/pull/200)
* feat: support new rule `method.content.type` [(#292)](https://github.com/tangcent/easy-api/pull/292)
* feat: support rule `param.http.type` for `RequestParam ` [(#298)](https://github.com/tangcent/easy-api/pull/298)
* feat: handle annotation `CookieValue` [(#300)](https://github.com/tangcent/easy-api/pull/300)

release v1.9.7.0.183.0

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiMethodDocClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt

- By default, split tags by `,\n` .
- Support property `api.tag.delimiter`

feat: support property `api.tag.delimiter`

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* opti: parse param as query by default [(#229)](https://github.com/tangcent/easy-yapi/pull/229)
* feat: [ScriptExecutor] support select field or method in the class. [(#231)](https://github.com/tangcent/easy-yapi/pull/231)
* feat: add rule alias `param.doc`/`method.doc`/`class.doc` [(#232)](https://github.com/tangcent/easy-yapi/pull/232)

release v2.0.1.0.183.0

---

idea-plugin/src/main/resources/.recommend.easy.api.config

before:
```properties
#ignore serialVersionUID
constant.field.ignore=serialVersionUID
```
after:
```properties
#ignore serialVersionUID
constant.field.ignore=groovy:it.name()=="serialVersionUID"
```

chore: fix recommend config for ignore serialVersionUID

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: always use json settings. [(#261)](https://github.com/tangcent/easy-yapi/pull/261)
* opti: new func: tool.traversal [(#265)](https://github.com/tangcent/easy-yapi/pull/265)
* opti: support rule `field.default.value` [(#266)](https://github.com/tangcent/easy-yapi/pull/266)
* fix: remove usage of Module.getModuleFilePath [(#267)](https://github.com/tangcent/easy-yapi/pull/267)

release v2.0.4

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: support rule util `session` [(#273)](https://github.com/tangcent/easy-yapi/pull/273)
* feat: support new method `annValue` for rule elements [(#274)](https://github.com/tangcent/easy-yapi/pull/274)
* opti: support rule `param.before`&`param.after` [(#275)](https://github.com/tangcent/easy-yapi/pull/275)
* opti: several recommended configs is not selected by default any longer [(#276)](https://github.com/tangcent/easy-yapi/pull/276)
* feat: new recommend configs [(#277)](https://github.com/tangcent/easy-yapi/pull/277)
* opti: support repeat validation annotation [(#278)](https://github.com/tangcent/easy-yapi/pull/278)

release v2.0.6

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt
idea-plugin/src/main/resources/.recommend.easy.api.config

opti: support param.before&param.after for methodDoc

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* opti: support org.springframework.lang.NonNull by recommend [(#302)](https://github.com/tangcent/easy-yapi/pull/302)
* opti: ignore org.springframework.validation.BindingResult by recommend [(#303)](https://github.com/tangcent/easy-yapi/pull/303)
* opti: support param.before&param.after for methodDoc [(#307)](https://github.com/tangcent/easy-yapi/pull/307)
* opti: preview recommendConfig with separator line [(#309)](https://github.com/tangcent/easy-yapi/pull/309)

release v2.1.0

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: always trim the name of folder [(#314)](https://github.com/tangcent/easy-yapi/pull/314)
* support param.required for methodDoc [(#315)](https://github.com/tangcent/easy-yapi/pull/315)
* opti: support `setter` for `toJson(5)` [(#318)](https://github.com/tangcent/easy-yapi/pull/318)
* opti: use raw as body and use unbox for query/form [(#320)](https://github.com/tangcent/easy-yapi/pull/320)

release v2.1.1

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt

fix：make yapi params ordered

---

idea-plugin/src/main/kotlin/com/itangcent/idea/sqlite/SqliteDataResourceHelper.kt

In the upcoming IDEA 2021.1 updated version of sqlite-jdbc is used, where `org.sqlite.SQLiteConfig#setBusyTimeout` signature has changed - see https://github.com/xerial/sqlite-jdbc/commit/926e281c03c508d982193d09da6ea2824d5f7e81.
---
close #332

opti: use `setPragma` instead of  `setBusyTimeout`

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* opti: support spring.ui by recommend [(330)](https://github.com/tangcent/easy-yapi/pull/330)
* opti: use `setPragma` instead of `setBusyTimeout` [(333)](https://github.com/tangcent/easy-yapi/pull/333)
* opti: refactor ApiDashboard [(335)](https://github.com/tangcent/easy-yapi/pull/335)

release v2.1.3

---

common-api/build.gradle
common-api/src/main/kotlin/com/itangcent/http/ApacheHttpClient.kt
idea-plugin/build.gradle
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/DefaultPostmanApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiInputHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiDashBoardExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiInputHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiClassExportRuleKeys.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/YapiDashboardDialog.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/SettingBinder.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt
idea-plugin/src/main/kotlin/com/itangcent/intellij/extend/BinderKit.kt
idea-plugin/src/main/kotlin/com/itangcent/suv/http/ConfigurableHttpClientProvider.kt

tick `loginMode`
config rule `yapi.export.before` like:
``````
yapi.export.before=groovy:```
httpClient.request().url("http://127.0.0.1:3000/api/user/login")
.method("POST")
.contentType("application/json")
.body(["email":"xxx@xxx.com","password":"*******"])
.call();
```
``````

opti: support login mode

---

idea-plugin/src/main/kotlin/com/itangcent/idea/config/CachedResourceResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/ClassApiExporterHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiMethodDocClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/sqlite/SqliteDataResourceHelper.kt

opti: support `param.doc` for export methodDoc

---

idea-plugin/src/main/kotlin/com/itangcent/idea/config/CachedResourceResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/SuvApiExportDialog.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/json/Json5Formatter.kt

set the cache time of content of URL:
e.g.
`url.cache.expire=1d12h`
The available time unit and conversion:
`1d`=`1day`=`24hours`
`1h`=`1hour`=`60minutes`
`1m`=`1minute`=`60seconds`
`1s`=`1second`
---
ref: #345

opti: support `url.cache.expire`

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* opti: `properties.additional` support url [(#345)](https://github.com/tangcent/easy-yapi/pull/345)
* opti: support `param.doc` for export methodDoc [(#347)](https://github.com/tangcent/easy-yapi/pull/347)
* fix:change the action name from Debug to ScriptExecutor [(#348)](https://github.com/tangcent/easy-yapi/pull/348)
* opti: support `url.cache.expire` [(#349)](https://github.com/tangcent/easy-yapi/pull/349)

release v2.1.5-rc

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* opti: `properties.additional` support url [(#345)](https://github.com/tangcent/easy-yapi/pull/345)
* opti: support `param.doc` for export methodDoc [(#347)](https://github.com/tangcent/easy-yapi/pull/347)
* fix:change the action name from Debug to ScriptExecutor [(#348)](https://github.com/tangcent/easy-yapi/pull/348)
* opti: support `url.cache.expire` [(#349)](https://github.com/tangcent/easy-yapi/pull/349)
* opti: add recommend third config [(#351)](https://github.com/tangcent/easy-yapi/pull/351)
* opti: show default built-in config in setting [(#353)](https://github.com/tangcent/easy-yapi/pull/353)

release v2.1.5

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt

fix: bind `settings.builtInConfig` as nullable

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: use `asKV` instead of `as KV<>` [(#364)](https://github.com/tangcent/easy-yapi/pull/364)

release v2.1.8

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt

- for `GET`: parse params as query
- for others: parse params as json body for multi-level display parameters

feat: [methodDoc-yapi] parse params as query for `GET`

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt

fix: not infer methods that return an interface type

---

IDEA_CHANGELOG.md
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: AbstractEasyApiConfigurable checkUI after createComponent [(#579)](https://github.com/tangcent/easy-yapi/pull/579)
* feat: update gui [(#578)](https://github.com/tangcent/easy-yapi/pull/578)
* fix: [curl] escape [&\] [(#577)](https://github.com/tangcent/easy-yapi/pull/577)
* test: add test case of YapiApiExporter [(#576)](https://github.com/tangcent/easy-yapi/pull/576)
* feat: support export apis to specified postman collection [(#575)](https://github.com/tangcent/easy-yapi/pull/575)
* feat: save yapi tokens in project scope [(#572)](https://github.com/tangcent/easy-yapi/pull/572)
* feat: show workspace with type [(#571)](https://github.com/tangcent/easy-yapi/pull/571)
* test: update CurlExporterTest [(#570)](https://github.com/tangcent/easy-yapi/pull/570)
* feat: support copy curl …

release v2.2.6

---

common-api/build.gradle
idea-plugin/build.gradle
idea-plugin/src/main/resources/.recommend.easy.api.config
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigLoaderTest.kt

recommend configs to support 
- com.fasterxml.jackson.databind.annotation.JsonNaming
- com.fasterxml.jackson.databind.PropertyNamingStrategies.UpperCamelCaseStrategy
- com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
- com.fasterxml.jackson.databind.PropertyNamingStrategies.LowerCaseStrategy
- com.fasterxml.jackson.databind.PropertyNamingStrategies.KebabCaseStrategy
- com.fasterxml.jackson.databind.PropertyNamingStrategies.LowerDotCaseStrategy

feat: recommend configs of Jackson JsonNaming(namingStrategy)

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: new rule `field.advanced` [(#605)](https://github.com/tangcent/easy-yapi/pull/605)
* fix: resolve Object as {} [(#603)](https://github.com/tangcent/easy-yapi/pull/603)
* chore: fix action text [(#601)](https://github.com/tangcent/easy-yapi/pull/601)
* feat: change action groups [(#600)](https://github.com/tangcent/easy-yapi/pull/600)
* feat: recommend configs of Jackson JsonNaming(namingStrategy) [(#595)](https://github.com/tangcent/easy-yapi/pull/595)
* test: add test case of RecommendConfigReader [(#591)](https://github.com/tangcent/easy-yapi/pull/591)
* test: add test case for ProjectHelperTest [(#589)](https://github.com/tangcent/easy-yapi/pull/589)
* chore: ignore `*Dialog`&`*Configurable`&`*Action.kt` for codecov [(#588)](https://github.com/tangcent/easy-yapi/pull/588)
* …

release v2.2.8

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.DirectorySpringMarkdownApiExporterTest.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.SpringMarkdownApiExporterTest.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.SpringUltimateMarkdownApiExporterTest.txt

fix: remove redundant table header in markdown

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: recommend config for `Jackson-JsonUnwrapped` [(#658)](https://github.com/tangcent/easy-yapi/pull/658)
* fix: remove redundant table header in markdown [(#654)](https://github.com/tangcent/easy-yapi/pull/654)
* feat: new rule `json.additional.field` [(#652)](https://github.com/tangcent/easy-yapi/pull/652)
* fix: read desc of class before compute by rule [(#649)](https://github.com/tangcent/easy-yapi/pull/649)
* feat: support quarkus [(#648)](https://github.com/tangcent/easy-yapi/pull/648)
* feat: support spring-feign [(#643)](https://github.com/tangcent/easy-yapi/pull/643)
* feat: support Condition [(#641)](https://github.com/tangcent/easy-yapi/pull/641)

release v2.3.0

---

idea-plugin/src/main/kotlin/com/itangcent/idea/utils/GsonExUtils.kt

EasyYapi 2.3.1.183.0 is binary incompatible with IntelliJ IDEA Ultimate IU-221.4501.155 due to the following problem
Field not found (1 problem)
```text
Access to unresolved field ObjectTypeAdapter.FACTORY (1 problem)
Method GsonExUtils.formatGson(Gson) contains a getstatic instruction referencing an unresolved field ObjectTypeAdapter.FACTORY. This can lead to NoSuchFieldError exception at runtime.
The field might have been declared in the super class: TypeAdapter
```

fix: remove usage of  ObjectTypeAdapter.FACTORY

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: [generic] auto fix http method [(#697)](https://github.com/tangcent/easy-yapi/pull/697)
* fix: use `any` instead of `forEach` to export api from superMethods [(#694)](https://github.com/tangcent/easy-yapi/pull/694)
* fix: remove usage of  ObjectTypeAdapter.FACTORY [(#693)](https://github.com/tangcent/easy-yapi/pull/693)
* feat: new Action FieldsToProperties [(#686)](https://github.com/tangcent/easy-yapi/pull/686)

release v2.3.2

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporter.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporterTest.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFeignRequestClassExporterTest.kt
idea-plugin/src/test/resources/api/feign/UserClient.java

fix: resolve mapping annotation for feign client

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* chore: add Fastjson support [(#745)](https://github.com/tangcent/easy-yapi/pull/745)
* feat: init recommend config even if no module be switched [(#744)](https://github.com/tangcent/easy-yapi/pull/744)
* fix: set `readTimeout` for read resource by url [(#743)](https://github.com/tangcent/easy-yapi/pull/743)
* feat: new method for rule context `class` [(#739)](https://github.com/tangcent/easy-yapi/pull/739)
* feat: resolve RequestMapping from interfaces [(#738)](https://github.com/tangcent/easy-yapi/pull/738)

release v2.3.6

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: not use '0' as example [(#771)](https://github.com/tangcent/easy-yapi/pull/771)
* fix: fix resize of ApiCallDialog [(#770)](https://github.com/tangcent/easy-yapi/pull/770)
* fix: fix  rule `field.default.value` [(#765)](https://github.com/tangcent/easy-yapi/pull/765)
* feat: not require confirmation to export apis from directory [(#766)](https://github.com/tangcent/easy-yapi/pull/766)

release v2.3.9

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: get resource with timeout [(#786)](https://github.com/tangcent/easy-yapi/pull/786)
* chore: remove usages of KitUtils.safe [(#785)](https://github.com/tangcent/easy-yapi/pull/785)
* feat: support new setting 'export selected method only' [(#783)](https://github.com/tangcent/easy-yapi/pull/783)

release v2.4.0

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: set resolveMulti to first in javax.validation.config [(#821)](https://github.com/tangcent/easy-yapi/pull/821)
* feat: add an option to update or skip existed apis in yapi [(#817)](https://github.com/tangcent/easy-yapi/pull/817)
* feat: asks how to convert enum on the first use [(#813)](https://github.com/tangcent/easy-yapi/pull/813)

release v2.4.5

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* amend: use :Log() instead of define [(#837)](https://github.com/tangcent/easy-yapi/pull/837)
* fix: parse FeignClient#path [(#835)](https://github.com/tangcent/easy-yapi/pull/835)
* feat: support export apis from actuator [(#834)](https://github.com/tangcent/easy-yapi/pull/834)
* fix: convert java.math.BigInteger to java.lang.Long [(#828)](https://github.com/tangcent/easy-yapi/pull/828)
* test: DefaultYapiApiHelperTest [(#824)](https://github.com/tangcent/easy-yapi/pull/824)

release v2.4.6

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: provider json.rule.enum.convert in recommendation [(#848)](https://github.com/tangcent/easy-yapi/pull/848)
* feat: populate field from mock [(#847)](https://github.com/tangcent/easy-yapi/pull/847)
* feat: new rule `yapi.save.before` & `yapi.save.after` [(#842)](https://github.com/tangcent/easy-yapi/pull/842)

release v2.4.7

---

common-api/build.gradle
idea-plugin/build.gradle
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/utils/IdeaFileChooserHelper.kt

fix: open FileChooser at AWT Thread

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* chore: polish ContextualPsiClassHelper [(#889)](https://github.com/tangcent/easy-yapi/pull/889)
* fix: support ConfigurationProperties("prefix") [(#888)](https://github.com/tangcent/easy-yapi/pull/888)
* fix: Gson no longer always parse number to double [(#885)](https://github.com/tangcent/easy-yapi/pull/885)
* chore: remove unnecessary log [(#881)](https://github.com/tangcent/easy-yapi/pull/881)

release v2.5.1

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: support swagger3 [(#897)](https://github.com/tangcent/easy-yapi/pull/897)
* feat: refresh button in [EasyApi > Remote] [(#895)](https://github.com/tangcent/easy-yapi/pull/895)
* fix: unescape api.tag.delimiter [(#894)](https://github.com/tangcent/easy-yapi/pull/894)
* fix: wrap annotation array parameter in script rule execute [(#893)](https://github.com/tangcent/easy-yapi/pull/893)

release v2.5.2

---

IDEA_CHANGELOG.md
build.gradle
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: provide aliases for several rule tools [(#925)](https://github.com/tangcent/easy-yapi/pull/925)
* chore: update version of intellij-kotlin to 1.4.5 [(#924)](https://github.com/tangcent/easy-yapi/pull/924)
* fix: fix api response in postman [(#923)](https://github.com/tangcent/easy-yapi/pull/923)
* feat: new rule tool: runtime [(#922)](https://github.com/tangcent/easy-yapi/pull/922)
* feat: support jakarta.validation [(#918)](https://github.com/tangcent/easy-yapi/pull/918)
* feat: support export apis from groovy [(#912)](https://github.com/tangcent/easy-yapi/pull/912)

release v2.5.4

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: output field.demo value to postman/markdown [(#958)](https://github.com/tangcent/easy-yapi/pull/958)
* chore: update version of intellij-kotlin to 1.5.0 [(#957)](https://github.com/tangcent/easy-yapi/pull/957)
* chore: polish SettingBinder [(#956)](https://github.com/tangcent/easy-yapi/pull/956)
* feat: read yapi token from config [(#955)](https://github.com/tangcent/easy-yapi/pull/955)
* fix: set _id back after save api to yapi success [(#952)](https://github.com/tangcent/easy-yapi/pull/952)

release v2.5.7

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/utils/GsonExUtils.kt
idea-plugin/src/main/kotlin/com/itangcent/utils/ExtensibleKit.kt
idea-plugin/src/main/resources/META-INF/plugin.xml

* amend: remove deprecated API usages [(#961)](https://github.com/tangcent/easy-yapi/pull/961)
* feat: output field.demo value to postman/markdown [(#958)](https://github.com/tangcent/easy-yapi/pull/958)
* chore: update version of intellij-kotlin to 1.5.0 [(#957)](https://github.com/tangcent/easy-yapi/pull/957)
* chore: polish SettingBinder [(#956)](https://github.com/tangcent/easy-yapi/pull/956)
* feat: read yapi token from config [(#955)](https://github.com/tangcent/easy-yapi/pull/955)
* fix: set _id back after save api to yapi success [(#952)](https://github.com/tangcent/easy-yapi/pull/952)

release v2.5.8

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestBuilderListener.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrap.kt

amend: modify several parameters in RequestRuleWrap nullable

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/AbstractStorage.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/LocalStorage.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SessionStorage.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/Storage.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/utils/JacksonUtilsTest.kt

fix: fix issue with SessionStorage not works

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* refactor: remove usage of KV  [(#1020)](https://github.com/tangcent/easy-yapi/pull/1020)
* fix: fix issue with SessionStorage not works  [(#1016)](https://github.com/tangcent/easy-yapi/pull/1016)
* fix: fix thread warning  [(#1012)](https://github.com/tangcent/easy-yapi/pull/1012)
* fix: added support for strict check in jakarta.validation and javax.validation  [(#1013)](https://github.com/tangcent/easy-yapi/pull/1013)

release 2.6.2

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* amend: remove CompensateRateLimiter  [(#1034)](https://github.com/tangcent/easy-yapi/pull/1034)
* feat: add rules `postman.format.after`, `yapi.format.after`  [(#1033)](https://github.com/tangcent/easy-yapi/pull/1033)
* chore: remove deprecated utils  [(#1024)](https://github.com/tangcent/easy-yapi/pull/1024)

release 2.6.3

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: Add recommended configuration for Jackson JsonPropertyOrder  [(#1048)](https://github.com/tangcent/easy-yapi/pull/1048)
* feat: Add new rule field.order.with  [(#1047)](https://github.com/tangcent/easy-yapi/pull/1047)
* feat: Apply field rules to getter and setter methods  [(#1044)](https://github.com/tangcent/easy-yapi/pull/1044)
* chore: polish YapiFormatter  [(#1043)](https://github.com/tangcent/easy-yapi/pull/1043)

release 2.6.4

---

gradle.properties
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/psi/DisableDocSupport.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/psi/DisableDocSupportTest.kt

feat: Support configuring doc.source.disable to disable documentation reading

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: Support configuring doc.source.disable to disable documentation reading  [(#1059)](https://github.com/tangcent/easy-yapi/pull/1059)

release 2.6.5

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: Add support for exporting APIs as .http files  [(#1076)](https://github.com/tangcent/easy-yapi/pull/1076)
* feat: support search in several dialogs  [(#1073)](https://github.com/tangcent/easy-yapi/pull/1073)
* Refactor: Preventing runtime.channel() from throwing exceptions on missing implementations  [(#1074)](https://github.com/tangcent/easy-yapi/pull/1074)

release 2.6.7

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
idea-plugin/src/main/kotlin/com/itangcent/intellij/extend/ActionContextKit.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt

feat: Enhance support for enum fields in 'field'

---

common-api/src/main/kotlin/com/itangcent/common/kit/KVUtils.kt
common-api/src/main/kotlin/com/itangcent/utils/AnyKit.kt
gradle.properties
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/CommentResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/RemoteConfigSettingsHelper.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/CommentResolverTest.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporterTest.kt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporterTest.testExportFromTestCtrlWithExpanded.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporterTest.testExportFromTestCtrlWithOutExpanded.txt

fix: resolve comment for custom enum field

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/RemoteConfigSettingsHelper.kt
idea-plugin/src/main/resources/.recommend.easy.api.config
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/cache/CachedRequestClassExporterTest.kt

fix: implement error handling in remoteConfigContent function

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/http/HttpClientFileSaver.kt

IntelliJ IDEA Ultimate (241.14494.127) compatibility warning. 
- 1 usage of scheduled for removal API
- EasyYapi 2.6.8.212.0 uses API scheduled for removal in future releases
- Scheduled for removal class usage (1)
- StringUtils (1) (scheduled for removal in a future release)
- Deprecated class StringUtils is referenced in FeignRequestClassExporter.resolveHeader(...). This class will be removed in a future release
- 1 deprecated API usage
- EasyYapi 2.6.8.212.0 uses deprecated API, which may be removed in future releases leading to binary and source code incompatibilities
- Deprecated method usage (1)
- PathKt.readText(Path) (1)
- Deprecated method PathKt.readText(Path) is invoked in HttpClientFileSaver.saveHttpFile(...)

chore: fix compatibility issues in compatibility verification

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/parts/pluginDescription.html
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt
idea-plugin/src/main/resources/META-INF/plugin.xml
plugin-script/release.sh

* fix: implement error handling in remoteConfigContent function  [(#1115)](https://github.com/tangcent/easy-yapi/pull/1115)
* fix: resolve comment for custom enum field  [(#1112)](https://github.com/tangcent/easy-yapi/pull/1112)
* fix: resolve configuration loading issue in several actions  [(#1111)](https://github.com/tangcent/easy-yapi/pull/1111)
* feat: optimize configuration loading logic for enhanced efficiency and reliability  [(#1107)](https://github.com/tangcent/easy-yapi/pull/1107)

release 2.6.9

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/EnhancedConfigReader.kt
idea-plugin/src/main/resources/META-INF/services/com.itangcent.intellij.config.ConfigProvider
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.EnhancedConfigReaderTest.EmptyRecommendEnhancedConfigReaderTest.log.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.EnhancedConfigReaderTest.SimpleEnhancedConfigReaderTest.log.txt

fix: resolve 'module_path' property resolution issue

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: resolve 'module_path' property resolution issue  [(#1137)](https://github.com/tangcent/easy-yapi/pull/1137)
* feat: added functionality to choose between apache and okHttp for sending HTTP requests via settings  [(#1132)](https://github.com/tangcent/easy-yapi/pull/1132)
* docs: remove Travis CI build status badge from README  [(#1136)](https://github.com/tangcent/easy-yapi/pull/1136)

release 2.7.1

---

common-api/src/main/kotlin/com/itangcent/http/RawContentType.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/DefaultPostmanApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanApiExporter.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/postman/DefaultPostmanApiHelperTest.kt

fix: correct content-type for Postman API export

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: remove Non-extendable interface usage  [(#1146)](https://github.com/tangcent/easy-yapi/pull/1146)
* chore: polish Postman API helper classes and cache management  [(#1145)](https://github.com/tangcent/easy-yapi/pull/1145)
* fix: correct content-type for Postman API export  [(#1144)](https://github.com/tangcent/easy-yapi/pull/1144)

release 2.7.2

---

.github/workflows/co.yml
idea-plugin/build.gradle.kts
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/utils/MavenHelper.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/ETHUtils.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/utils/MavenHelperTest.kt

feat(script): add support for 'mavenId()' in 'class'

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.CustomizedDirectorySpringMarkdownApiExporterTest.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.DirectorySpringMarkdownApiExporterTest.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.postman.PostmanApiExporterTest.DirectorySpringPostmanApiExporterTest.txt
idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.yapi.YapiApiExporterTest.DirectorySpringYapiApiExporterTest.txt

feat: omit content-type header when no parameters are present

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptor.kt
idea-plugin/src/main/resources/META-INF/services/com.itangcent.idea.plugin.api.export.yapi.YapiSaveInterceptor
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/condition/OnDocConditionTest.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptorTest.kt

feat: add 'yapi.no_update.description' to stop api description updates

---

idea-plugin/src/main/resources/.recommend.easy.api.config
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigLoaderTest.kt

feat: support Jackson JsonView

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: support Jackson JsonView  [(#1162)](https://github.com/tangcent/easy-yapi/pull/1162)
* feat: add 'yapi.no_update.description' to stop api description updates  [(#1170)](https://github.com/tangcent/easy-yapi/pull/1170)
* feat: omit content-type header when no parameters are present  [(#1169)](https://github.com/tangcent/easy-yapi/pull/1169)
* build: update IntelliJ plugin version from 1.14.2 to 1.17.1  [(#1166)](https://github.com/tangcent/easy-yapi/pull/1166)
* feat(script): add support for 'mavenId()' in 'class'  [(#1155)](https://github.com/tangcent/easy-yapi/pull/1155)
* chore: add missing space in log message for setting Postman privateToken  [(#1148)](https://github.com/tangcent/easy-yapi/pull/1148)

release 2.7.3

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt

fix: update methods in ScriptRuleParser to avoid return types with parameter type erasure

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/CustomSpringControllerAnnotationResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/CustomSpringRequestMappingResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/DefaultSpringControllerAnnotationResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/DefaultSpringRequestMappingResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SimpleSpringRequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringClassName.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringControllerAnnotationResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporter.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestMappingResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/StandardSpringControllerAnnotationResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/StarandSpringRequestMappingResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/StandardJdkRuleParser.kt
idea-plugin/src/main/resources/META-INF/services/com.itangcent.idea.plugin.api.export.spring.SpringControllerAnnotationResolver
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporterTest.kt
idea-plugin/src/test/resources/annotation/MyController.java
idea-plugin/src/test/resources/api/CustomCtrl.java
idea-plugin/src/test/resources/spring/AliasFor.java

feat: Add Support for Meta-Spring Controller Annotations

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* feat: Introduces a new ApiDashboardPanel for API testing  [(#1191)](https://github.com/tangcent/easy-yapi/pull/1191)
* chore: remove the usage of ThrottleHelper  [(#1189)](https://github.com/tangcent/easy-yapi/pull/1189)
* feat: Add Support for Meta-Spring Controller Annotations  [(#1187)](https://github.com/tangcent/easy-yapi/pull/1187)
* fix: correct YapiSaveInterceptor order for no_update.description config  [(#1185)](https://github.com/tangcent/easy-yapi/pull/1185)

release 2.7.5

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/dashboard/ApiDashboardPanel.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/dashboard/ApiDashboardService.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/dashboard/ApiDashboardToolWindow.kt

feat: Improve ApiDashboard lifecycle management and context handling

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* fix: several ApiExport actions cannot export method docs  [(#1201)](https://github.com/tangcent/easy-yapi/pull/1201)

release 2.7.7

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestBuilderListener.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanExportRuleKeys.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatFolderHelperTest.kt

- Update rule keys to consistently start with "postman." prefix:
- CLASS_POST_PRE_REQUEST
- COLLECTION_POST_PRE_REQUEST
- CLASS_POST_TEST
- COLLECTION_POST_TEST
- Keep original keys as aliases for backward compatibility

refactor(postman): standardize rule key naming pattern

---

IDEA_CHANGELOG.md
gradle.properties
idea-plugin/parts/pluginChanges.html
idea-plugin/src/main/resources/META-INF/plugin.xml

* refactor: Enhance EasyApiSettingAI layout  [(#1209)](https://github.com/tangcent/easy-yapi/pull/1209)
* refactor: Refactor SPI BeanProvider logic  [(#1208)](https://github.com/tangcent/easy-yapi/pull/1208)
* feat: Add AI-powered translation support for API documentation  [(#1207)](https://github.com/tangcent/easy-yapi/pull/1207)
* refactor(postman): standardize rule key naming pattern  [(#1206)](https://github.com/tangcent/easy-yapi/pull/1206)
* feat: Add support for AI-powered method inference  [(#1205)](https://github.com/tangcent/easy-yapi/pull/1205)
* fix: Fix project cache size always showing as zero in settings  [(#1204)](https://github.com/tangcent/easy-yapi/pull/1204)

release 2.7.8

---

.github/workflows/pr-package.yml

build: Enhance PR workflow to comment on both issues and PRs

---

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrap.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrapTest.kt

Add new functions to the script 'api' object to access query parameters, form parameters, and path parameters with wrapper objects that provide full manipulation capabilities. This makes it easier for rule scripts to retrieve and manage request parameters in a more object-oriented way.
- Add methods to retrieve parameters: params(), param(name), params(name)
- Add methods to retrieve form parameters: formParams(), formParam(name), formParams(name)
- Add methods to retrieve path parameters: pathParams(), pathParam(name), pathParams(name)

feat: Enhance script object 'api' with parameter accessor methods

---

common-api/src/main/kotlin/com/itangcent/http/RequestUtils.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/config/CachedResourceResolver.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/icons/EasyIcons.kt
idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/HttpSettingsHelperImpl.kt
idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/markdown/TemplateMarkdownFormatterTest.kt
idea-plugin/src/test/kotlin/com/itangcent/test/StringResource.kt

chore: Replace deprecated `URL` constructor calls with `asUrl()` extension
