.gitignore, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiCallAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiDashBoardAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/MarkdownExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/PostmanExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/YapiExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultDocParseHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiIdeaParseHandle.kt
=> try resolve link to yapi

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt
=> make sure the path prefix with '/' for yapi

build.gradle, gradle.properties, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/YapiDashBoardAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/YapiExportAction.kt, idea-plugin/src/main/resources/META-INF/plugin.xml
=> fix json.rule for yapi export/dashboard

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/MethodReturnInfer.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/PsiHelper.kt
Try infer the actual return type of the method whose return type is an interface
fix #36
=> opti MethodReturnInferHelper

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt
=> use json instead of form for add cart of yapi

README.md
=> change support mark

README.md, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt
=> support rule [param.ignore]

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt
- new rules:
- [method.additional.header]:provide additional header for request
- [method.additional.param]:provide additional param for request
- [method.additional.response.header]:provide additional header for response
---
see #78
=> some new rules

common-api/src/main/kotlin/com/itangcent/common/utils/KitUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/psi/ResourceHelper.kt
- new rules:
- [doc.class]:additional doc for class
- [class.prefix.path]:prefix path for all api in class
---
see #78
=> new rule[doc.class]&[class.prefix.path]

idea-plugin/build.gradle
=> update version of intellij-kotlin to 0.1.6-SNAPSHOT

common-api/src/main/kotlin/com/itangcent/common/utils/KitUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/FieldsToJsonAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/SuvExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SimpleMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SimpleRequestClassExporter.kt
=> support new rule: `api.name`

IDEA_CHANGELOG.md, common-api/src/main/kotlin/com/itangcent/common/utils/KitUtils.kt, idea-plugin/build.gradle, idea-plugin/parts/pluginChanges.html, idea-plugin/parts/pluginDescription.html, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/MethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/call/ApiCaller.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SimpleMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SimpleRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/script/GroovyActionExtLoader.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SpringClassName.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/CacheAble.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/DefaultCacheAle.kt, idea-plugin/src/main/resources/META-INF/services/com.itangcent.common.SetupAble, src/main/resources/META-INF/services/com.itangcent.common.SetupAble
=> Merge from 'easy-api'

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt
=> read recommendConfig by default charset utf-8

.gitignore, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/resources/.recommend.easy.api.config
=> provide recommend config for yapi mock

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt
=> opti: resolve enum constant in methodInfer

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt, idea-plugin/src/main/resources/.recommend.easy.api.config
=> Merge easy api

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/DefaultPostmanApiHelper.kt
=>  limit postman api request

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt
=> fix yapi example value

common-api/src/main/kotlin/com/itangcent/common/model/Request.kt, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/CommentResolver.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/RequestHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/RuleComputorKit.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/RuleToolUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/KVKit.kt
=> resolve generic info in super class

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt
=> findAttrOfClass  from read thread

common-api/src/main/kotlin/com/itangcent/common/model/Request.kt, common-api/src/main/kotlin/com/itangcent/common/model/URL.kt, common-api/src/main/kotlin/com/itangcent/http/RequestUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultRequestHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.kt
=> feat: show attr of param with @requestbody for `yapi`

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiRequestKit.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt
- config:
```properties
api.open=#open
api.tag[#open]=open
```
- code:
```java
/**
* 更新用户信息
*
* @open
*/
@PostMapping("update")
public IResult update(UserInfo userInfo) {
return Result.success(userInfo);
}
```
---
see #178
=> feat: support new rule `api.open`

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt
=> feat: support switch notice at `Setting`

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt
=> opti: input new token if the old one be deleted.

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/DebugAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultRequestHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrap.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/DebugDialog.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/DebugDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/RuleToolUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/StandardJdkRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/KtHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/RegexUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SimpleStringDiffHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SpringClassName.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/StringDiffHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/DefaultFileSaveHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/DefaultFileSelectHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/ExtensibleKit.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/FileSaveHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/FileSelectHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/IdeaFileChooserHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/suv/http/ConfigurableHttpClientProvider.kt
- chore: polish GsonKit
- feat: support new rule `export.after`
- feat: add methods to RequestRuleWrap
- feat: new tool `files`
- feat: `Debug` enhancement
=> Merge easy-api

IDEA_CHANGELOG.md, build.gradle, common-api/src/main/kotlin/com/itangcent/common/model/Request.kt, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/parts/pluginDescription.html, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/CommentResolver.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/RequestHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/resources/META-INF/plugin.xml
- feat: new rule `method.content.type` 
- feat: new rule `param.without.ann.type`
=> support new rules

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SpringClassName.kt
see https://github.com/tangcent/easy-api/issues/297
see https://github.com/tangcent/easy-api/issues/299
=> feat: support rule `param.http.type`

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt
see https://github.com/tangcent/easy-yapi/issues/203#issuecomment-654577910
=> fix: keep required from RequestParam. 

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt
Example:
```java
@RestController
@RequestMapping("/idea-plugins/test")
public class TestController {
@GetMapping("/{key}/upload/{id:[0-9]+}")
public String test01(@PathVariable String key,
@PathVariable String id,
@RequestParam String param) {
return "success";
}
}
```
=> Support Postman export "Path Variables"

IDEA_CHANGELOG.md, build.gradle, common-api/build.gradle, gradle.properties, idea-plugin/build.gradle, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
- feat: support Postman export "Path Variables"  [(#213)](https://github.com/tangcent/easy-yapi/pull/213)
- opti: resolve relative path. [(#53)](https://github.com/Earth-1610/intellij-kotlin/pull/53)
=> release v1.9.8.0.183.0

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt
=> fix: fix required for query with GET(yapi)

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: fix required for query with GET. [(#305)](https://github.com/tangcent/easy-api/pull/305)
* fix: keep parameter info to query or form. [(#307)](https://github.com/tangcent/easy-api/pull/307)
* chore: rename Action `Debug` -> `ScriptExecutor`. [(#308)](https://github.com/tangcent/easy-api/pull/308)
* feat: support property `api.tag.delimiter` [(#223)](https://github.com/tangcent/easy-yapi/pull/223)
=> release v1.9.9.0

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/PostmanExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultFormatFolderHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/Folder.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/FormatFolderHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatFolderHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiDashBoardExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
see https://learning.postman.com/docs/writing-scripts/pre-request-scripts/
-  Add pre-request scripts to entire collections as well as to folders within collections.
This script will execute before every request in this collection or folder. 
-  Add test scripts to entire collections as well as to folders within collections.
These tests will execute after every request in this collection. 
---
close #225
=> support `postman.prerequest&postman.test` for collection.

.travis.yml, IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/RuleToolUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/resources/META-INF/plugin.xml, plugin-script/build_plugin.sh, plugin-script/delete_draft_tag.sh, plugin-script/package_plugin.sh, plugin-script/push_tag.sh
* feat: new rules `class.postman.prerequest`&`class.postman.test` [(#312)](https://github.com/tangcent/easy-api/pull/312)
* feat: new rule `collection.postman.prerequest`&`collection.postman.test` [(#314)](https://github.com/tangcent/easy-api/pull/314)
* feat: new Setting [postman] wrapCollection & autoMergeScript [(#317)](https://github.com/tangcent/easy-api/pull/317)
=> release v2.0.0.0.183.0

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/GroovyRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/SuvRuleParser.kt
import pr https://github.com/Earth-1610/intellij-kotlin/pull/62
to resolve several kt expressions
fix #245
=> chore: update version of intellij-kotlin to 0.7.8-SNAPSHOT

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/resources/.recommend.easy.api.config
fix #248 
```properties
enum.use.name=groovy:it.type().name()=="java.lang.String"
enum.use.ordinal=groovy:it.type().name()=="int"
enum.use.ordinal=groovy:it.type().name()=="java.lang.Integer"
```
=> feat: new recommend config [support_enum_common]

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
=> fix: fix class/type #isExtend

IDEA_CHANGELOG.md, build.gradle, common-api/build.gradle, gradle.properties, idea-plugin/build.gradle, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: support DeferredResult by recommend [(#250)](https://github.com/tangcent/easy-yapi/pull/250)
* feat: new recommend config \[support_enum_common] [(#251)](https://github.com/tangcent/easy-yapi/pull/251)
* fix: fix class/type #isExtend [(#253)](https://github.com/tangcent/easy-yapi/pull/253)
=> release v2.0.3.0

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/group/JsonSetting.kt
=> fix: always use json settings

common-api/src/main/kotlin/com/itangcent/common/kit/KVUtils.kt, common-api/src/main/kotlin/com/itangcent/http/RequestUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/MarkdownFormatType.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelper.kt
- SIMPLE: simple columns, include name、type、desc
- ULTIMATE: more columns than simple, include name、type、required、default、desc
=> opti: support tow markdown format type

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form
=> fix: fix setting GUI

build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
=> release v2.0.5

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/resources/.recommend.easy.api.config
new recommend configs: `Jackson_JsonIgnoreProperties`&`javax.validation(grouped)`
fix #185 
fix #259
=> feat: new recommend configs

idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/FileType.kt, idea-plugin/src/main/resources/META-INF/services/com.itangcent.common.spi.SetupAble
The supported of Scala makes too much compatibility challenges.
The plugin with Scala supported will be released at [releases](https://github.com/tangcent/easy-yapi/releases) only.
=> scala will not be supported by default

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/PostmanJson5FormatType.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/KVKit.kt
=> feat: support json5 for postman

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: support json5 for postman [(#286)](https://github.com/tangcent/easy-yapi/pull/286)
=> release v2.0.7

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SimpleRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/utils/SpringClassName.kt
=> opti: support rule `class.is.ctrl`

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: new action `ToJson5` [(#300)](https://github.com/tangcent/easy-yapi/pull/300)
=> release v2.0.9

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/Folder.kt
=> fix: always trim the name of folder

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/MethodDocHelper.kt
support param.required for methodDoc
=> support param.required for methodDoc

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/FieldsToJsonAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/DefaultMethodDocClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/group/JsonSetting.kt
=> opti: support `setter` for `toJson(5)`

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/CustomInfoImpl.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt, idea-plugin/src/main/resources/META-INF/services/com.itangcent.intellij.CustomInfo
| type  |  for body  | for query/form |
| ------------ | ------------ | ------------ |
| int | int | int |
| int[] | int[] | int |
=> opti: use raw as body and use unbox for query/form

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: resolve on-demand import [(#84)](https://github.com/Earth-1610/intellij-kotlin/pull/84)
* opti: import default packages for `kotlin`&`scala` [(#85)](https://github.com/Earth-1610/intellij-kotlin/pull/85)
* opti: log for method infer [(#325)](https://github.com/tangcent/easy-yapi/pull/325)
=> release v2.1.2

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* opti: support login mode [(340)](https://github.com/tangcent/easy-yapi/pull/340)
* opti: support built-in config [(341)](https://github.com/tangcent/easy-yapi/pull/341)
=> release v2.1.4

common-api/build.gradle, common-api/src/main/kotlin/com/itangcent/common/model/Request.kt, common-api/src/main/kotlin/com/itangcent/common/utils/FileSizeUtils.kt, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/config/MyResourceResolver.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/cache/DefaultFileApiCacheRepository.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/cache/FileApiCache.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigLoader.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ScriptExecutorDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/sqlite/SqliteDataResourceHelper.kt
`properties.additional` support url like:
```
properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/idea-plugin/src/main/resources/.recommend.easy.api.config
```
=> opti: `properties.additional` support url

.gitignore, idea-plugin/parts/pluginDescription.html
change  Debug to ScriptExecutor
=> fix:change the action name from Debug to ScriptExecutor

common-api/src/main/kotlin/com/itangcent/common/kit/KVUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigLoader.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/sqlite/SqliteDataResourceHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/utils/ResourceUtils.kt, idea-plugin/src/main/resources/.default.built.in.easy.api.config, plugin-script/package_plugin.sh
```properties
#properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/javax.validation.mock.config
#properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/swagger.config
#properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/swagger.advanced.config
```
=> opti: show default built-in config in setting

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: bind `settings.builtInConfig` as nullable [(#358)](https://github.com/tangcent/easy-yapi/pull/358)
=> release v2.1.6

common-api/src/main/kotlin/com/itangcent/common/constant/Attrs.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiRequestKit.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/KVKit.kt, idea-plugin/src/main/kotlin/com/itangcent/utils/ExtensibleKit.kt
=> fix: parse `Header`&`Param` by `ExtensibleKit.fromJson`

codecov.yml, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt
=> fix: block recursive call getValue

idea-plugin/src/main/kotlin/com/itangcent/intellij/util/KVKit.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/utils/KVKitTest.kt
=> fix: resolveCycle in KVKit

idea-plugin/src/main/kotlin/com/itangcent/idea/utils/JacksonUtils.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/utils/JacksonUtilsTest.kt
=> fix: configure FAIL_ON_EMPTY_BEANS as false

common-api/src/main/kotlin/com/itangcent/utils/FuncKit.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/AdaptiveMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/BundledMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/ConfigurableShellFileMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/FileMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/RemoteMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/ShellFileMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/SystemProvider.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/render/AdaptiveMarkdownRenderTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/render/BundledMarkdownRenderTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/render/ConfigurableShellFileMarkdownRenderTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/render/RemoteMarkdownRenderTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/utils/DefaultSystemProviderTest.kt, idea-plugin/src/test/kotlin/com/itangcent/mock/ImmutableSystemProvider.kt, idea-plugin/src/test/kotlin/com/itangcent/test/HttpClientProviderMockBuilder.kt
provider a bundled markdown render
ref: https://github.com/JetBrains/markdown
=> feat: bundled markdown render

common-api/src/main/kotlin/com/itangcent/http/ApacheHttpClient.kt, idea-plugin/src/main/kotlin/com/itangcent/suv/http/ConfigurableHttpClientProvider.kt
=> fix: Ignore SSL certificate in ApacheHttpClient

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ScriptExecutorDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/ContextualPsiClassHelper.kt
`containingClass` : the class containing the member
`defineClass` : the class  which declare the member.
---
fix #573
=> feat: `method&field` support  containingClass&defineClass

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: `method&field` support  containingClass&defineClass [(#585)](https://github.com/tangcent/easy-yapi/pull/585)
* feat: new recommend config to support [not ignore `static final` field] [(#583)](https://github.com/tangcent/easy-yapi/pull/583)
* fix: apply setting not work [(#582)](https://github.com/tangcent/easy-yapi/pull/582)
=> release v2.2.7

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AdditionalField.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/AdditionalParseHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/ClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultAdditionalParseHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiAdditionalParseHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/ContextualPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelper.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiPsiClassHelperTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/utils/ContextualPsiClassHelperTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelperTest.kt
```properties
json.additional.field[com.itangcent.model.UserInfo]={"name":"label","defaultValue":"genius","type":"java.lang.String","desc":"label of the user","required":true}
json.additional.field[com.itangcent.model.UserInfo#name]={"name":"firstName","defaultValue":"tang","type":"java.lang.String","desc":"a family name","required":false}
json.additional.field[com.itangcent.model.UserInfo#age]={"name":"order","defaultValue":"12","type":"int","desc":"order of the age in family","required":true}
```
=> feat: new rule `json.additional.field`

idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultDocParseHelperTest.kt, idea-plugin/src/test/resources/cases/LinkCase.java, idea-plugin/src/test/resources/cases/NestedClass.java, idea-plugin/src/test/resources/cases/NestedClassB.java
=> test: Test case of [DefaultDocParseHelper]

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: support @RequestLine、@Headers、@Param、@Body [(#676)](https://github.com/tangcent/easy-yapi/pull/676)
* test: Test case of [DefaultDocParseHelper] [(#675)](https://github.com/tangcent/easy-yapi/pull/675)
* feat: try parse api info from super methods [(#674)](https://github.com/tangcent/easy-yapi/pull/674)
* fix: [json5] remove lead blank lines [(#673)](https://github.com/tangcent/easy-yapi/pull/673)
* feat: improve Settings UI [(#672)](https://github.com/tangcent/easy-yapi/pull/672)
* feat: [recommend] converter of reactivestreams.Publisher [(#667)](https://github.com/tangcent/easy-yapi/pull/667)
* chore: update docs [(#665)](https://github.com/tangcent/easy-yapi/pull/665)
* fix: resolve multi-line root desc as block comments [(#664)](https://github.com/tangcent/easy-yapi/pull/664) …
=> release v2.3.1

third/generic.spring.demo.config
http://easyyapi.com/documents/generic.html
=> feat: generic.spring.demo.config

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/BasicAnAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/log/CustomLogConfig.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/CommonSettingsHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/xml/ApplicationSettings.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/CommonSettingsHelperTest.kt
=> feat:  support change log charset by settings

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/psi/PsiMethodSet.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/psi/PsiMethodUtil.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/psi/PsiMethodSetTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/psi/PsiMethodUtilTest.kt, idea-plugin/src/test/resources/api/IUserApi.java, idea-plugin/src/test/resources/api/UserApiImpl.java, idea-plugin/src/test/resources/model/Result.java, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporterTest.testExportFromUserApi.txt
=> feat: export apis from implements

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* chore: update swagger.config [(#712)](https://github.com/tangcent/easy-yapi/pull/712)
* fix: resolve mapping annotation for feign client [(#711)](https://github.com/tangcent/easy-yapi/pull/711)
* feat: export apis from implements [(#709)](https://github.com/tangcent/easy-yapi/pull/709)
* feat:  support change log charset by settings [(#708)](https://github.com/tangcent/easy-yapi/pull/708)
* test: DefaultFileSaveHelperTest [(#707)](https://github.com/tangcent/easy-yapi/pull/707)
=> release v2.3.3

common-api/src/main/kotlin/com/itangcent/http/RequestUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/format/SimpleJsonFormatterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.DirectorySpringMarkdownApiExporterTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.GenericMethodMarkdownApiExporterTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.SpringMarkdownApiExporterTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.SpringUltimateMarkdownApiExporterTest.txt, third/markdown.cn.config
markdown rules: [MarkdownExportRuleKeys](https://github.com/tangcent/easy-yapi/blob/6bd65c94f9f75564e15131619663fb3926ee1add/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownExportRuleKeys.kt)
demo: [third/markdown.cn.config](https://github.com/tangcent/easy-yapi/blob/6bd65c94f9f75564e15131619663fb3926ee1add/third/markdown.cn.config)
---
fix #715
=> feat: provide rules to customize markdown

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/Writer.kt
=> fix: fix Writer

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.RecommendConfigReaderTest.SimpleRecommendConfigReaderTest.foreach.txt
https://github.com/Earth-1610/intellij-kotlin/pull/154
https://github.com/Earth-1610/intellij-kotlin/pull/155
=> chore: update version of intellij-kotlin to 1.1.7

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: fix Writer [(#726)](https://github.com/tangcent/easy-yapi/pull/726)
* feat: provide rules to customize tables in markdown [(#724)](https://github.com/tangcent/easy-yapi/pull/724)
* chore: update markdown.cn.config [(#721)](https://github.com/tangcent/easy-yapi/pull/721)
=> release v2.3.5

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/DefaultSpringRequestMappingResolver.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporterTest.kt, idea-plugin/src/test/resources/api/IUserApi.java, idea-plugin/src/test/resources/api/UserApiImpl.java
=> feat: resolve RequestMapping from implements

idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigLoaderTest.kt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.RecommendConfigReaderTest.SimpleRecommendConfigReaderTest.foreach.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigLoaderTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigSettingsHelperTest.txt
close https://github.com/tangcent/easy-yapi/pull/734
=> chore: add Fastjson support

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: rename module quarkus to jaxrs [(#751)](https://github.com/tangcent/easy-yapi/pull/751)
* fix: resolve enum without constructor [(Earth-1610/#159)](https://github.com/Earth-1610/intellij-kotlin/pull/159)
=> release v2.3.7

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: interval sleep during parsing [(#757)](https://github.com/tangcent/easy-yapi/pull/757)
=> release v2.3.8

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/condition/AnnotatedCondition.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiCallAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/MarkdownExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/PostmanExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/SuvExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/YapiExportAction.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/MethodFilter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/suv/SuvApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/SuvApiExportDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/IntelligentSettingsHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/xml/ApplicationSettings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/DefaultFileSaveHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/IdeaFileChooserHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/intellij/extend/ActionContextKit.kt, idea-plugin/src/main/kotlin/com/itangcent/utils/FileKit.kt, plugin-script/test.sh
=> feat: support new setting 'export selected method only'

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt
=> feat: resolve suspend function in kotlin

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: resolve suspend function in kotlin [(#790)](https://github.com/tangcent/easy-yapi/pull/790)
* feat: new rule `enum.use.custom` [(#168)](https://github.com/Earth-1610/intellij-kotlin/pull/168)
=> release v2.4.1

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/jaxrs/JAXRSRequestClassExporter.kt
=> fix: resolve doc of fields for param annotated with @BeanParam

IDEA_CHANGELOG.md, build.gradle, common-api/build.gradle, gradle.properties, idea-plugin/build.gradle, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: enum auto select field by type [(#797)](https://github.com/tangcent/easy-yapi/pull/797)
* fix: resolve doc of fields for param annotated with @BeanParam [(#796)](https://github.com/tangcent/easy-yapi/pull/796)
=> release v2.4.2

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: new setting  `Postman > build example` [(#802)](https://github.com/tangcent/easy-yapi/pull/802)
=> release v2.4.3

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: resolve desc of return type [(#807)](https://github.com/tangcent/easy-yapi/pull/807)
* fix: support parse apis in several modules to one collection [(#806)](https://github.com/tangcent/easy-yapi/pull/806)
=> release v2.4.4

docs/cn/Home.md, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiCachedApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptor.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/condition/ConditionOnSetting.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/condition/OnSettingCondition.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/AskWithApplyAllDialog.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/AskWithApplyAllDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ChooseWithTipDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/PostmanExportMode.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/Settings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/YapiExportMode.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/xml/ApplicationSettings.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/swing/DefaultMessagesHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/swing/MessagesHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/spi/SpiCompositeLoader.kt, idea-plugin/src/main/resources/META-INF/services/com.itangcent.idea.plugin.api.export.yapi.YapiSaveInterceptor, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiExporterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptorTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/EnumProcessInitializerTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelperTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/swing/MessagesHelperTest.kt, idea-plugin/src/test/kotlin/com/itangcent/mock/EmptyMessagesHelper.kt
=> feat: add an option to update or skip existed apis in yapi

third/javax.validation.config
=> fix: set resolveMulti to first in javax.validation.config

idea-plugin/src/main/resources/.recommend.easy.api.config
=> fix: convert java.math.BigInteger to java.lang.Long

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporter.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/feign/RequestLineRequestMappingResolverTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFeignRequestClassExporterTest.kt, idea-plugin/src/test/resources/api/feign/PrimitiveUserClient.java
=> fix: parse FeignClient#path

README.md, README_en.md, common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/idea/config/CachedResourceResolver.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/ClassApiExporterHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/DefaultPostmanApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanCachedApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/configurable/AbstractEasyApiConfigurable.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/AbstractApiDashboardDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiDashboardDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/AskWithApplyAllDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/YapiDashboardDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/render/AdaptiveMarkdownRender.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/sqlite/SqliteDataResourceHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/CustomizedPsiClassHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/JacksonUtils.kt, idea-plugin/src/main/kotlin/com/itangcent/spi/SpiCompositeLoader.kt, idea-plugin/src/test/kotlin/com/itangcent/test/ResultLoader.kt
=> amend: use :Log() instead of define

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/ReservedResponseHandle.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiExporter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiClassExportRuleKeys.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/SuvRuleContext.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/ReservedResponseHandleTest.kt
=> feat: new rule `yapi.save.before` & `yapi.save.after`

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.RecommendConfigReaderTest.SimpleRecommendConfigReaderTest.foreach.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigLoaderTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigSettingsHelperTest.txt
=> feature: provider json.rule.enum.convert in recommendation

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* polish: update icons [(#855)](https://github.com/tangcent/easy-yapi/pull/855)
* feat: highlight new content in Settings->Recommend [(#853)](https://github.com/tangcent/easy-yapi/pull/853)
* feat: support remote config setting [(#852)](https://github.com/tangcent/easy-yapi/pull/852)
=> release v2.4.8

IDEA_CHANGELOG.md, build.gradle, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: fix the icons and buttons disappeared [(#869)](https://github.com/tangcent/easy-yapi/pull/869)
* fix: remove invalid attributes for create postman collections [(#868)](https://github.com/tangcent/easy-yapi/pull/868)
* fix: open FileChooser at AWT Thread [(#863)](https://github.com/tangcent/easy-yapi/pull/863)
=> release v2.4.9

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiLinkResolver.kt
=> chore: update log

IDEA_CHANGELOG.md, build.gradle, common-api/build.gradle, gradle.properties, idea-plugin/build.gradle, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* fix: check group with `javax.validation.groups.Default` [(#877)](https://github.com/tangcent/easy-yapi/pull/877)
* amend: group actions in pop [(#876)](https://github.com/tangcent/easy-yapi/pull/876)
=> release v2.5.0

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt, idea-plugin/src/test/resources/model/ValidationGroupedDemoDto.java
=> fix: wrap annotation array parameter in script rule execute

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiRequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/utils/StringKit.kt, idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/kotlin/com/itangcent/utils/StringKitKtTest.kt
=> fix: unescape api.tag.delimiter

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/CompositeRequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultRequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/postman/PostmanRequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrap.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiRequestBuilderListener.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultRequestBuilderListenerTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/rule/RequestRuleWrapTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/ScriptClassContextBaseTest.kt
=> feat: new script method `class.toObject`

common-api/build.gradle, idea-plugin/build.gradle, idea-plugin/src/main/kotlin/com/itangcent/intellij/util/FileType.kt
=> feat: support export apis from groovy

idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigLoaderTest.kt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.RecommendConfigReaderTest.SimpleRecommendConfigReaderTest.foreach.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigLoaderTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.settings.helper.RecommendConfigSettingsHelperTest.txt
=> feat: support jakarta.validation

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/StandardJdkRuleParser.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/utils/DefaultModuleHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/utils/NonReentrant.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/rule/StandardJdkRuleParserTest.kt, idea-plugin/src/test/kotlin/com/itangcent/utils/NonReentrantTest.kt
=> feat: new rule tool: runtime

common-api/build.gradle, idea-plugin/build.gradle
=> chore: update version of intellij-kotlin to 1.4.5

IDEA_CHANGELOG.md, build.gradle.kts, gradle.properties, idea-plugin/build.gradle.kts, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml, idea-plugin/src/test/kotlin/com/itangcent/testFramework/PluginContextLightCodeInsightFixtureTestCase.kt, idea-plugin/src/test/resources/model/UserInfo.java, plugin-script/release.sh
* build: use Kotlin DSL script build project [(#933)](https://github.com/tangcent/easy-yapi/pull/933)
* feat: support config ignore_irregular_api_method [(#929)](https://github.com/tangcent/easy-yapi/pull/929)
---
close #932
=> release v2.5.5

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt
=> fix: set _id back after save api to yapi success

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelperTest.kt
=> feat: read yapi token from config

gradle.properties, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/AbstractYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/DefaultYapiApiHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/YapiDashboardDialog.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/XmlSettingBinder.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/support/IdeaSupport.kt
=> amend: remove deprecated API usages

README.md
=> doc: declare Requirements & Compatibility

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml, plugin-script/release.sh
* fix: fix swagger3.config  [(#996)](https://github.com/tangcent/easy-yapi/pull/996)
* doc: declare Requirements & Compatibility  [(#994)](https://github.com/tangcent/easy-yapi/pull/994)
* build: update workflows name  [(#995)](https://github.com/tangcent/easy-yapi/pull/995)
* build: update workflows  [(#989)](https://github.com/tangcent/easy-yapi/pull/989)
* amend: remove support of GroovyActionExt  [(#991)](https://github.com/tangcent/easy-yapi/pull/991)
* build: update scripts  [(#988)](https://github.com/tangcent/easy-yapi/pull/988)
* amend: clear uiWeakReference  [(#983)](https://github.com/tangcent/easy-yapi/pull/983)
* amend: modify several parameters in RequestRuleWrap nullable  [(#984)](https://github.com/tangcent/easy-yapi/pull/984)
---
closes #968,#971,#986
=> release 2.5.9

idea-plugin/src/main/resources/.recommend.easy.api.config
=> fix: fix support for com.fasterxml.jackson.annotation.JsonUnwrapped

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/parts/pluginDescription.html, idea-plugin/src/main/resources/META-INF/plugin.xml, plugin-script/release.sh
* chore: update pluginDescription  [(#1002)](https://github.com/tangcent/easy-yapi/pull/1002)
* fix: process correct class when clicking class in multi-class Kotlin file  [(#1000)](https://github.com/tangcent/easy-yapi/pull/1000)
* fix: fix support for com.fasterxml.jackson.annotation.JsonUnwrapped  [(#999)](https://github.com/tangcent/easy-yapi/pull/999)
=> release 2.6.0

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: ignore some common classes  [(#1009)](https://github.com/tangcent/easy-yapi/pull/1009)
* fix: refined config behavior for mocking enum fields  [(#1008)](https://github.com/tangcent/easy-yapi/pull/1008)
=> release 2.6.1

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigSettingsHelper.kt, idea-plugin/src/main/resources/.recommend.easy.api.config, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/settings/helper/RecommendConfigLoaderTest.kt
=> fix: added support for strict check in jakarta.validation and javax.validation

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: Enhance support for enum fields in 'field'  [(#1083)](https://github.com/tangcent/easy-yapi/pull/1083)
* amend: refactor ResolveMultiPath enum to encapsulate url selection logic  [(#1079)](https://github.com/tangcent/easy-yapi/pull/1079)
* amend: Restrict api selection to single item in ApiCall  [(#1078)](https://github.com/tangcent/easy-yapi/pull/1078)
=> release 2.6.8

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/EnhancedConfigReader.kt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.EnhancedConfigReaderTest.EmptyRecommendEnhancedConfigReaderTest.log.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.config.EnhancedConfigReaderTest.SimpleEnhancedConfigReaderTest.log.txt
=> fix: fix issue where the configuration was not being loaded before actions were performed

third/swagger3.config
=> feat: add support for io.swagger.v3.oas.annotations.media.Schema annotation

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: add rules `param.name`, `param.type`  [(#1128)](https://github.com/tangcent/easy-yapi/pull/1128)
* feat: add support for io.swagger.v3.oas.annotations.media.Schema annotation  [(#1127)](https://github.com/tangcent/easy-yapi/pull/1127)
* fix: fix issue where the configuration was not being loaded before actions were performed  [(#1123)](https://github.com/tangcent/easy-yapi/pull/1123)
* feat: Replace gson and jsoup with IntelliJ code style for JSON/XML/HTML formatting  [(#1119)](https://github.com/tangcent/easy-yapi/pull/1119)
=> release 2.7.0

idea-plugin/build.gradle.kts
=> build: update IntelliJ plugin version from 1.14.2 to 1.17.1

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* build: update project dependencies  [(#1180)](https://github.com/tangcent/easy-yapi/pull/1180)
* chore: remove AskWithApplyAllDialog form file  [(#1181)](https://github.com/tangcent/easy-yapi/pull/1181)
* test: add unit tests for ClassApiExporterHelper  [(#1179)](https://github.com/tangcent/easy-yapi/pull/1179)
* refactor: replace nullable properties with lateinit for improved initialization in CommentResolver  [(#1178)](https://github.com/tangcent/easy-yapi/pull/1178)
* fix: update methods in ScriptRuleParser to avoid return types with parameter type erasure  [(#1176)](https://github.com/tangcent/easy-yapi/pull/1176)
=> release 2.7.4

idea-plugin/src/main/resources/META-INF/services/com.itangcent.idea.plugin.api.export.yapi.YapiSaveInterceptor
=> fix: correct YapiSaveInterceptor order for no_update.description config

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: implement cookie persistence in ApiDashboardPanel  [(#1198)](https://github.com/tangcent/easy-yapi/pull/1198)
* feat: Improve ApiDashboard lifecycle management and context handling  [(#1197)](https://github.com/tangcent/easy-yapi/pull/1197)
=> release 2.7.6

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/ApiExportAction.kt
=> fix: several ApiExport actions cannot export method docs

.github/workflows/pr-release.yml, IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: Implement template-based Markdown formatting for API documentation (#1216)
* build: update Kotlin daemon JVM arguments (#1215)
* refactor: improve AI response content handling (#1214)
* feat: Support Local LLM service (#1212)
* build(ci): add GitHub Actions workflow for automated releases (#1213)
=> release 2.7.9

gradle.properties, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/ClassApiExporterHelper.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultLinkResolver.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultLinkResolverTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/feign/FeignRequestClassExporterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporterTest.kt, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiLinkResolverTest.kt, idea-plugin/src/test/resources/model/Result.java, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.CustomizedDirectorySpringMarkdownApiExporterTest.txt, idea-plugin/src/test/resources/result/com.itangcent.idea.plugin.api.export.markdown.MarkdownApiExporterTest.DirectorySpringMarkdownApiExporterTest.txt
=> feat: improve link resolution in Markdown Documentation Comments

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: improve link resolution in Markdown Documentation Comments (#1220)
* build: add commit message validation workflow (#1219)
* fix: escape special characters in markdown template tables (#1218)
=> release 2.8.0

.github/workflows/pr-package.yml
=> build(ci): Add workflow to package plugin and notify on PRs

idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptor.kt, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/EasyApiSettingGUI.form, idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/YapiExportMode.kt, idea-plugin/src/main/resources/META-INF/services/com.itangcent.idea.plugin.api.export.yapi.YapiSaveInterceptor, idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSaveInterceptorTest.kt
=> feat: support skipping unchanged API updates to YAPI

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html, idea-plugin/src/main/resources/META-INF/plugin.xml
* feat: Enhance script object 'api' with parameter accessor methods (#1241)
* refactor: Standardize capitalization in form labels (#1236)
* build: update release label in auto-label workflow configuration (#1237)
* build: Enhance PR workflow to comment on both issues and PRs (#1239)
* feat: Add multi-window console logging capability (#1235)
* refactor: implement cache invalidation for CachedYapiApiHelper (#1233)
* build: add cleanBin task in build.gradle.kts (#1232)
* feat: ignore fields from java.lang system classes to prevent complex exported types (#1229)
* feat: support skipping unchanged API updates to YAPI (#1224)
* refactor: Remove unused charset setting from log configuration (#1231)
* build(ci): Add workflow to package plugin and notify on PRs (#1226)
=> release 2.8.1

gradle/wrapper/gradle-wrapper.properties, idea-plugin/build.gradle.kts, idea-plugin/src/main/resources/META-INF/plugin.xml
=> fix: Fix compatibility with IntelliJ IDEA Ultimate IU-251.26094.121+

IDEA_CHANGELOG.md, gradle.properties, idea-plugin/parts/pluginChanges.html
* fix: Format default values as strings in YAPI export (#1261)
* feat: Add support for processing inner classes in API export (#1258)
=> release 2.8.3
